# Istio Gateway for POC
# Use TLS PASSTHROUGH so WSO2 services terminate TLS themselves.
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: wso2-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: tls
        protocol: TLS
      tls:
        mode: PASSTHROUGH
      hosts:
        - "apim.local"
        - "is.local"
---
# VirtualService for APIM (SNI based routing)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: apim-vs
  namespace: wso2
spec:
  hosts:
    - "apim.local"
  gateways:
    - istio-system/wso2-gateway
  tls:
    - match:
        - port: 443
          sniHosts:
            - "apim.local"
      route:
        - destination:
            host: wso2-apim-am-service
            port:
              number: 9443
---
# VirtualService for IS (SNI based routing)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: is-vs
  namespace: wso2
spec:
  hosts:
    - "is.local"
  gateways:
    - istio-system/wso2-gateway
  tls:
    - match:
        - port: 443
          sniHosts:
            - "is.local"
      route:
        - destination:
            host: wso2-is
            port:
              number: 9443
