apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: orbstack-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.228.240-192.168.228.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: metallb-system
